version: '3.9'

services:
  db:
    image: postgres:15
    container_name: isocial_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - isocial_pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  app:
    build:
      context: ./
    container_name: isocial
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/isocial
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./isocial-key-vault-isocial-cert-20240429.pem:/etc/nginx/isocial-key-vault-isocial-cert-20240429.pem
    ports:
      - "443:443"
    depends_on:
      - app

volumes:
  isocial_pg_data:
